name: Python package

on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10.13"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      - name: Lint with ruff
        run: |
          ruff check owlapy --line-length=200
      - name: Test with pytest
        run: |
          wget https://files.dice-research.org/projects/Ontolearn/KGs.zip
          unzip KGs.zip
          python -m pytest -p no:warnings -x

# Removed because of an error is generated when trying to create the report.
# It happens because of some pytorch conflict. One of our tests namely test_z_do_last_ebr_retrieval.py uses pytorch
# (also via dicee but the exact root is unknown) and it deletes the tmp files before the coverage can access it.
# In case of update of coverage report (on new releases) just do it manually (run it locally).
#
#      - name: Coverage report
#        run: |
#          pip install coverage
#          coverage run -m pytest
#          coverage report -m